name: flintrock

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-18.04
          # - macos-11
        python-version:
          - "3.7"
          - "3.8"
          - "3.9"
          # - "3.10"
    name: ${{ matrix.os }} / Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - run: "pip install -r requirements/maintainer.pip"
      - run: "pytest"
      - run: python setup.py sdist bdist_wheel
      - uses: actions/upload-artifact@v3
        with:
          name: Flintrock Standalone - ${{ matrix.os }}
          path: dist/Flintrock-*-standalone-*.zip
      - uses: actions/upload-artifact@v3
        with:
          name: Flintrock Wheel
          path: dist/Flintrock-*.whl
