name: flintrock

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-20.04
          - macos-14
        python-version:
          # Update the artifact upload steps below if modifying
          # this list of Python versions.
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
          - "3.14"
    name: ${{ matrix.os }} / Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - run: "pip install -r requirements/maintainer.pip"
      - run: "pytest"
      - run: python -m build
      - uses: actions/upload-artifact@v3
        # Use the latest supported Python to build a standalone package.
        if: ${{ matrix.python-version == '3.14' }}
        with:
          name: Flintrock Standalone - ${{ matrix.os }}
          path: dist/Flintrock-*-standalone-*.zip
      - uses: actions/upload-artifact@v3
        # Use the oldest supported Python to build a wheel.
        if: ${{ matrix.os == 'ubuntu-20.04' && matrix.python-version == '3.9' }}
        with:
          name: Flintrock Wheel
          path: dist/Flintrock-*.whl
